version: '3'

services:
  trojan-panel-caddy:
    image: caddy:2.6.2
    container_name: trojan-panel-caddy
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/caddy/config.json:/tpdata/caddy/config.json"
      - "/tpdata/cert/:/tpdata/cert/certificates/acme-v02.api.letsencrypt.org-directory/${TROJAN_PANEL_DOMAIN}/"
      - "/tpdata/web/:/tpdata/web/"
      - "/tpdata/caddy/logs/:/tpdata/caddy/logs/"
    command: caddy run --config /tpdata/caddy/config.json

  trojan-panel:
    image: jonssonyan/trojan-panel
    container_name: trojan-panel
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/web/:/tpdata/trojan-panel/webfile/"
      - "/tpdata/trojan-panel/logs/:/tpdata/trojan-panel/logs/"
      - "/tpdata/trojan-panel/export:/tpdata/trojan-panel/export"
      - "/tpdata/trojan-panel/template:/tpdata/trojan-panel/template"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=${MYSQL_IP}"
      - "mariadb_port=${MYSQL_PORT}"
      - "mariadb_user=${MYSQL_USER}"
      - "mariadb_pas=${MYSQL_PASSWORD}"
      - "redis_host=${REDIS_IP}"
      - "redis_port=${REDIS_PORT}"
      - "redis_pass=${REDIS_PASSWORD}"

  trojan-panel-ui:
    image: jonssonyan/trojan-panel-ui
    container_name: trojan-panel-ui
    restart: always
    network_mode: host
    volumes:
      - "/tpdata/trojan-panel-ui/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/tpdata/cert/:/tpdata/cert/"
